### ISSUE TITLE
WorldGuard incompatibility

### ISSUE THREAD

**Issue by MaxedOut1** [TitaniumMC/Titanium#126]
Worldguard crashes on launch. Im using the newest worldguard version for 1.8: worldguard-6.2.jar

```
[14:39:43 INFO]: [WorldGuard] Enabling WorldGuard v6.1.3-SNAPSHOT;c904242
[14:39:43 ERROR]: Error occurred while enabling WorldGuard v6.1.3-SNAPSHOT;c904242 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.google.common.util.concurrent.ListeningExecutorService com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()'
        at com.sk89q.worldguard.internal.guava.cache.LocalCache.<clinit>(LocalCache.java:77) ~[?:?]
        at com.sk89q.worldguard.internal.guava.cache.LocalCache$LocalLoadingCache.<init>(LocalCache.java:4798) ~[?:?]
        at com.sk89q.worldguard.internal.guava.cache.CacheBuilder.build(CacheBuilder.java:793) ~[?:?]
        at com.sk89q.worldguard.session.SessionManager.<init>(SessionManager.java:62) ~[?:?]
        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:170) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:422) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:473) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:547) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:511) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:466) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:716) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:148) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:39:43 INFO]: [WorldGuard] Disabling WorldGuard v6.1.3-SNAPSHOT;c904242
[14:39:43 INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[14:39:43 ERROR]: Error occurred while disabling WorldGuard v6.1.3-SNAPSHOT;c904242 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.sk89q.worldguard.protection.managers.RegionContainerImpl.unloadAll()" because "this.container" is null
        at com.sk89q.worldguard.bukkit.RegionContainer.unload(RegionContainer.java:138) ~[?:?]
        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:287) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:422) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:473) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:547) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:511) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:466) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:716) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:148) ~[patched_1.8.8.jar:git-Titanium-JENKINS-main-8]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by c0dingnoobi** [comment]
u have to use version 6.2.1 
>  Im using the newest worldguard version for 1.8: worldguard-6.2.jar

no your not 
first line in stracktrace states that ur using version 6.1.3

**Comment by P3ridot** [comment]
> u have to use version 6.2.1
> 
> > Im using the newest worldguard version for 1.8: worldguard-6.2.jar
> 
> no your not first line in stracktrace states that ur using version 6.1.3

Actually for some reason 6.1.3 is marked as 6.2 on `dev.bukkit.org` and even file is names with 6.2...

**Comment by MaxedOut1** [comment]
> > u have to use version 6.2.1
> > > Im using the newest worldguard version for 1.8: worldguard-6.2.jar
> > 
> > 
> > no your not first line in stracktrace states that ur using version 6.1.3
> 
> Actually for some reason 6.1.3 is marked as 6.2 on `dev.bukkit.org` and even file is names with 6.2...

Yes i noticed that, thats why I specified the name of the jar i downloaded.

Also thank you for the quick reply! 6.2.1 works perfectly!
