### ISSUE TITLE
Pearling into player causes exception

### ISSUE THREAD

**Issue by c0dingnoobi** [TitaniumMC/Titanium#127]
1. Load titanium default config without any plugins
2. Pearl into another player

Stacktrace: 
```[17:57:45 WARN]: Entity threw exception at world:6.200082678951454,6.281411965528365,97.54467346207707
[17:57:45 WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_8_R3.BlockPosition.getX()" because "blockposition" is null
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.WorldBorder.a(WorldBorder.java:34)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.WorldBorder.isInBounds(WorldBorder.java:32)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.EntityEnderPearl.a(EntityEnderPearl.java:46)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:163)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.EntityEnderPearl.t_(EntityEnderPearl.java:129)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1912)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.World.g(World.java:1879)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1708)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:643)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1121)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:438)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:948)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:759)
[17:57:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:148)
[17:57:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by P3ridot** [comment]
Fixed in `dev` branch - jenkins should soon finish building...

**Comment by c0dingnoobi** [comment]
pro
