### ISSUE TITLE
/server - IOException

### ISSUE THREAD

**Issue by Regomy** [TitaniumMC/Titanium#133]
> ver
[10:14:45 INFO]: Checking version, please wait...
[10:14:45 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://jenkins.titanvale.net/job/Titanium/job/main/api/json?lastCompletedBuild[number]
[10:14:45 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[10:14:45 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[10:14:45 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[10:14:45 WARN]:        at java.net.URL.openStream(Unknown Source)
[10:14:45 WARN]:        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[10:14:45 WARN]:        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
[10:14:45 WARN]:        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:107)
[10:14:45 WARN]:        at com.destroystokyo.paper.PaperVersionFetcher.fetchDistanceFromSiteApi(PaperVersionFetcher.java:72)
[10:14:45 WARN]:        at com.destroystokyo.paper.PaperVersionFetcher.getUpdateStatusMessage(PaperVersionFetcher.java:40)
[10:14:45 WARN]:        at com.destroystokyo.paper.PaperVersionFetcher.getVersionMessage(PaperVersionFetcher.java:28)
[10:14:45 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:204)
[10:14:45 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$000(VersionCommand.java:33)
[10:14:45 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:188)
[10:14:45 WARN]:        at java.lang.Thread.run(Unknown Source)
[10:14:45 INFO]: 
>> This server is running Titanium (JENKINS-main-8) - Implementing API version 1.8.8-R0.1-SNAPSHOT
>> Latest version couldn't be obtained!

**Comment by c0dingnoobi** [comment]
@P3ridot thats the same as in discord support thread "version command error"

**Comment by P3ridot** [comment]
Yeah, but I can't really do much about that. I could only make these error prettier, but that's all... It's jenkins issue or maybe some hosting protection. I'll bet this second option since it occurs only on some people servers...

**Comment by Regomy** [comment]
> Yeah, but I can't really do much about that. I could only make these error prettier, but that's all... It's jenkins issue or maybe some hosting protection. I'll bet this second option since it occurs only on some people servers...

Checked through localhost.

**Comment by P3ridot** [comment]
oh okay, but whatever - it's only cosmetic... maybe jenkins do something weird shit but who knows
