### ISSUE TITLE
Error while unloading world from SlimeWorldManager

### ISSUE THREAD

**Issue by Drizz1** [TitaniumMC/Titanium#77]
```
[07:53:37] [Server thread/WARN]: [BedWars1058] Task #48395 for BedWars1058 v21.12.1 generated an exception
java.lang.ClassCastException: class com.grinderwolf.swm.nms.v1_8_R3.CustomChunkLoader cannot be cast to class net.minecraft.server.v1_8_R3.ChunkRegionLoader (com.grinderwolf.swm.nms.v1_8_R3.CustomChunkLoader is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @111aa6cd; net.minecraft.server.v1_8_R3.ChunkRegionLoader is in unnamed module of loader 'app')
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.unloadWorld(CraftServer.java:1190) ~[patched_1.8.8.jar:git-Titanium-4db4f7d584]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.unloadWorld(CraftServer.java:1151) ~[patched_1.8.8.jar:git-Titanium-4db4f7d584]
	at org.bukkit.Bukkit.unloadWorld(Bukkit.java:523) ~[patched_1.8.8.jar:git-Titanium-4db4f7d584]
	at com.andrei1058.bedwars.arena.mapreset.slime.SlimeAdapter.onRestart(SlimeAdapter.java:156) ~[?:?]
	at com.andrei1058.bedwars.arena.Arena.restart(Arena.java:1297) ~[?:?]
	at com.andrei1058.bedwars.arena.tasks.GameRestartingTask.run(GameRestartingTask.java:108) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.8.8.jar:git-Titanium-4db4f7d584]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:412) ~[patched_1.8.8.jar:git-Titanium-4db4f7d584]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1003) ~[patched_1.8.8.jar:git-Titanium-4db4f7d584]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:414) ~[patched_1.8.8.jar:git-Titanium-4db4f7d584]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:905) ~[patched_1.8.8.jar:git-Titanium-4db4f7d584]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:716) ~[patched_1.8.8.jar:git-Titanium-4db4f7d584]
	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:140) ~[patched_1.8.8.jar:git-Titanium-4db4f7d584]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by P3ridot** [comment]
It connected with #75

**Comment by P3ridot** [comment]
In the latest release 0.8.2 everything should works, if not I will reopen this issue
