### ISSUE TITLE
WorldGuard is not working

### ISSUE THREAD

**Issue by Fredh1000** [TitaniumMC/Titanium#79]
This is the error that appears in the console when starting the server:

[07:59:20] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.1.3-SNAPSHOT;c904242
[07:59:20] [Server thread/ERROR]: Error occurred while enabling WorldGuard v6.1.3-SNAPSHOT;c904242 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.google.common.util.concurrent.ListeningExecutorService com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()'
	at com.sk89q.worldguard.internal.guava.cache.LocalCache.<clinit>(LocalCache.java:77) ~[?:?]
	at com.sk89q.worldguard.internal.guava.cache.LocalCache$LocalLoadingCache.<init>(LocalCache.java:4798) ~[?:?]
	at com.sk89q.worldguard.internal.guava.cache.CacheBuilder.build(CacheBuilder.java:793) ~[?:?]
	at com.sk89q.worldguard.session.SessionManager.<init>(SessionManager.java:62) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:170) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:422) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:498) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:457) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:577) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:541) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:496) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:743) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:140) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:59:20] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v6.1.3-SNAPSHOT;c904242
[07:59:20] [Server thread/INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[07:59:20] [Server thread/ERROR]: Error occurred while disabling WorldGuard v6.1.3-SNAPSHOT;c904242 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.sk89q.worldguard.protection.managers.RegionContainerImpl.unloadAll()" because "this.container" is null
	at com.sk89q.worldguard.bukkit.RegionContainer.unload(RegionContainer.java:138) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:287) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:422) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:498) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:457) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:577) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:541) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:496) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:743) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:140) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by P3ridot** [comment]
Solution is using WorldGuard 6.2.1 (yeah, that for 1.12.2)
