### ISSUE TITLE
Citizens2 doesn't work properly

### ISSUE THREAD

**Issue by ByOuHuang** [TitaniumMC/Titanium#80]
Citizens2 doesn't work properly under Titanium, it works fine in Paper.

```
[Citizens] Task #114 for Citizens v2.0.28-SNAPSHOT (build 2359) generated an exception
java.lang.NullPointerException: metadata
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:39) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at io.netty.channel.DefaultChannelConfig.setRecvByteBufAllocator(DefaultChannelConfig.java:325) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:79) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:75) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.citizensnpcs.nms.v1_8_R3.network.EmptyChannel.<init>(EmptyChannel.java:14) ~[?:?]
	at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl.initNetworkManager(NMSImpl.java:1326) ~[?:?]
	at net.citizensnpcs.nms.v1_8_R3.network.EmptyNetworkManager.<init>(EmptyNetworkManager.java:12) ~[?:?]
	at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:246) ~[?:?]
	at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:82) ~[?:?]
	at net.citizensnpcs.nms.v1_8_R3.entity.HumanController.createEntity(HumanController.java:54) ~[?:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:510) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:412) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1090) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:414) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:992) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:803) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:140) ~[patched_1.8.8.jar:git-Titanium-a75a59f0be]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

Java version: Oracle-11
Citizens2 Link: https://github.com/CitizensDev/Citizens2

**Comment by P3ridot** [comment]
Citizens don't work due to their code that doesn't support newer netty versions

**Comment by ByOuHuang** [comment]
> 公民无法工作，因为他们的代码不支持较新的网络版本

https://github.com/TitaniumMC/Titanium/issues/80#issuecomment-1261000769

**Comment by P3ridot** [comment]
I'm gonna try my best, but currently I don't have much time. I will resolve this ASAP

**Comment by P3ridot** [comment]
The problem is currently on the size of Citizens. I created PR with fixes, but now we can only wait until they merge them into master branch ¯\_(ツ)_/¯
