### ISSUE TITLE
Problems with LibertyBans MySQL driver/processor

### ISSUE THREAD

**Issue by milk7202** [TitaniumMC/Titanium#81]
Titanium-0.9.0 is having problems with [LibertyBans](https://www.spigotmc.org/resources/libertybans.81063/), this only occurs on titanium when mysql is activated, causing libertybans not to connect with the DB and starts using HyperSQL (local)

```
[19:04:11 INFO]: [LibertyBans] Enabling LibertyBans v1.0.4
[19:04:12 INFO]: Conducting start phase...
[19:04:12 WARN]: The values in your configuration are invalid. Please correct the issue and run /libertybans reload. For now, the default configuration will be used.
space.arim.dazzleconf.error.BadValueException: For key mode:
Encountered an error while loading the configuration. 
Reason: The wrong type was entered. The value should be an enum value, but it was really MySQL
Some examples of valid input: , ANSI_SQL
Extra info: None
        at space.arim.dazzleconf.error.BadValueException$Builder.build(BadValueException.java:95) ~[?:?]
        at space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getEnum(FlexibleTypeImpl.java:181) ~[?:?]
        at space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getEnumUnchecked(FlexibleTypeImpl.java:186) ~[?:?]
        at space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getObject0(FlexibleTypeImpl.java:312) ~[?:?]
        at space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getObject(FlexibleTypeImpl.java:275) ~[?:?]
        at space.arim.dazzleconf.internal.processor.Composition.processObject(Composition.java:89) ~[?:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.getProcessedValue(ProcessorBase.java:126) ~[?:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.process(ProcessorBase.java:97) ~[?:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.createConfig(ProcessorBase.java:71) ~[?:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.createFromProcessor(ProcessorBase.java:160) ~[?:?]
        at space.arim.dazzleconf.internal.processor.MapProcessor.createChildConfig(MapProcessor.java:60) ~[?:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.createNested(ProcessorBase.java:156) ~[?:?]
        at space.arim.dazzleconf.internal.processor.Composition.processObject(Composition.java:61) ~[?:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.getProcessedValue(ProcessorBase.java:126) ~[?:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.process(ProcessorBase.java:97) ~[?:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.createConfig(ProcessorBase.java:71) ~[?:?]
        at space.arim.dazzleconf.factory.ConfigurationFormatFactory.fromRawMap(ConfigurationFormatFactory.java:174) ~[?:?]
        at space.arim.dazzleconf.factory.ConfigurationFormatFactory.load(ConfigurationFormatFactory.java:126) ~[?:?]
        at space.arim.dazzleconf.factory.DelegatingConfigurationFactory.load(DelegatingConfigurationFactory.java:57) ~[?:?]
        at space.arim.dazzleconf.factory.AbstractConfigurationFactory.load(AbstractConfigurationFactory.java:42) ~[?:?]
        at space.arim.libertybans.core.config.ConfigHolder.loadFromPath(ConfigHolder.java:116) ~[?:?]
        at space.arim.libertybans.core.config.ConfigHolder.lambda$reload$0(ConfigHolder.java:87) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
[19:04:12 INFO]: LibertyBansPool-HyperSQL - Starting...
[19:04:13 INFO]: dataFileCache open start
[19:04:13 INFO]: dataFileCache open end
[19:04:13 INFO]: LibertyBansPool-HyperSQL - Driver does not support get/set network timeout for connections. (feature not supported)
[19:04:13 INFO]: LibertyBansPool-HyperSQL - Added connection org.hsqldb.jdbc.JDBCConnection@730308e1
[19:04:13 INFO]: LibertyBansPool-HyperSQL - Start completed.
[19:04:14 INFO]: Flyway Community Edition 8.2.0 by Redgate
[19:04:14 INFO]: Database: jdbc:hsqldb:file:/home/container/plugins/LibertyBans/internal/hypersql/punishments-database;sql.enforce_refs=true;hsqldb.tx_interrupt_rollback=true;sql.sys_index_names=true;hsqldb.default_table_type=cached;sql.enforce_types=true;sql.restrict_exec=true;sql.enforce_names=true (HSQL Database Engine 2.6)
[19:04:14 INFO]: Successfully validated 7 migrations (execution time 00:00.082s)
[19:04:14 INFO]: Current version of schema "PUBLIC": 20
[19:04:14 INFO]: Schema "PUBLIC" is up to date. No migration necessary.
[19:04:14 INFO]: Finished start phase in 1.993 seconds
```

**Comment by P3ridot** [comment]
The reason is probably updated mysql library in Titanium. When I get back home I will try to resolve this issue

**Comment by P3ridot** [comment]
For me with MariaDB and LibertyBans 1.0.4 everything worked. Could you give more information? What value in `synchronization.mode` did you passed?

**Comment by milk7202** [comment]
> For me with MariaDB and LibertyBans 1.0.4 everything worked. Could you give more information? What value in `synchronization.mode` did you passed?

MySQL, the problem is now obvious, bad configuration on my part

**Comment by milk7202** [comment]
> For me with MariaDB and LibertyBans 1.0.4 everything worked. Could you give more information? What value in `synchronization.mode` did you passed?

MySQL, the problem is now obvious, bad configuration on my part
