### ISSUE TITLE
WorldGuard incompatibility issues

### ISSUE THREAD

**Issue by ByOuHuang** [TitaniumMC/Titanium#85]
[15:25:41 INFO]: [WorldGuard] Enabling WorldGuard v6.1.3-SNAPSHOT;c904242
[15:25:41 ERROR]: Error occurred while enabling WorldGuard v6.1.3-SNAPSHOT;c904242 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
        at com.sk89q.worldguard.internal.guava.cache.LocalCache.<clinit>(LocalCache.java:77) ~[?:?]
        at com.sk89q.worldguard.internal.guava.cache.LocalCache$LocalLoadingCache.<init>(LocalCache.java:4798) ~[?:?]
        at com.sk89q.worldguard.internal.guava.cache.CacheBuilder.build(CacheBuilder.java:793) ~[?:?]
        at com.sk89q.worldguard.session.SessionManager.<init>(SessionManager.java:62) ~[?:?]
        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:170) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:422) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:498) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:457) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:577) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:541) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:496) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:743) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:140) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
[15:25:41 INFO]: [WorldGuard] Disabling WorldGuard 

- [ ]  #v6.1.3-SNAPSHOT;c904242

[15:25:41 INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[15:25:41 ERROR]: Error occurred while disabling WorldGuard v6.1.3-SNAPSHOT;c904242 (Is it up to date?)
java.lang.NullPointerException: null
        at com.sk89q.worldguard.bukkit.RegionContainer.unload(RegionContainer.java:138) ~[?:?]
        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:287) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:422) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:498) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:457) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:577) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:541) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:496) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:743) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:140) ~[patched_1.8.8.jar:git-Titanium-62b5adf30f]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]

WorldGuard Plugin Link: https://dev.bukkit.org/projects/worldguard/files/956770

**Comment by P3ridot** [comment]
Use WorldGuard 6.2.1 (yes that for 1.12.2)

**Comment by P3ridot** [comment]
#79
