### ISSUE TITLE
Startup Crash (okaeri-configs)

### ISSUE THREAD

**Issue by DrakMC** [TitaniumMC/Titanium#96]
```
eu.okaeri.configs.exception.OkaeriException: failed to initialize net.titanium.config.TitaniumConfig [class eu.okaeri.configs.yaml.bukkit.YamlBukkitConfigurer]
	at eu.okaeri.configs.ConfigManager.create(ConfigManager.java:55)
	at net.titanium.Titanium.createServerConfig(Titanium.java:68)
	at net.titanium.Titanium.loadServerConfig(Titanium.java:87)
	at net.titanium.Titanium.<init>(Titanium.java:39)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:263)
	at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:76)
	at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(DedicatedPlayerList.java:13)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:180)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:743)
	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:140)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Cannot extract 'spigot.timings.enabled': not deep enough (ended at index 1 [timings:null])
	at eu.okaeri.configs.migrate.view.RawConfigView.valueExtract(RawConfigView.java:91)
	at eu.okaeri.configs.migrate.view.RawConfigView.get(RawConfigView.java:25)
	at net.titanium.config.MigrationHelper.lambda$putConfig$0(MigrationHelper.java:62)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.titanium.config.MigrationHelper.putConfig(MigrationHelper.java:56)
	at net.titanium.config.MigrationHelper.putSpigotConfig(MigrationHelper.java:33)
	at net.titanium.config.TitaniumConfig.load(TitaniumConfig.java:420)
	at eu.okaeri.configs.OkaeriConfig.load(OkaeriConfig.java:421)
	at net.titanium.Titanium.lambda$createServerConfig$1(Titanium.java:79)
	at eu.okaeri.configs.ConfigManager.create(ConfigManager.java:52)
	... 10 more
```

**Comment by P3ridot** [comment]
In latest `dev` build everything should work
